# Generated by Django 5.1.7 on 2025-03-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_userprofile_security_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='security_answer',
            new_name='security_answer_hash',
        ),
    ]
