# Generated by Django 5.1.7 on 2025-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_security_answer_userprofile_security_answer_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='security_answer_hash',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
