# Generated by Django 5.1.7 on 2025-03-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_userprofile_security_answer_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='security_answer',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
